# nlu/synonym_map.py
# Maps user query keywords to dataset genre labels

SYNONYM_MAP = {
    # Action
    "action": ["Action"],
    "fighting": ["Action"],
    "battle": ["Action"],
    "fight": ["Action"],
    "intense": ["Action"],
    "combat": ["Action"],
    # Adventure
    "adventure": ["Adventure"],
    "journey": ["Adventure"],
    "quest": ["Adventure"],
    "explore": ["Adventure"],
    # Comedy
    "comedy": ["Comedy"],
    "funny": ["Comedy"],
    "humor": ["Comedy"],
    "humour": ["Comedy"],
    "lighthearted": ["Comedy"],
    "hilarious": ["Comedy"],
    "laugh": ["Comedy"],
    # Drama
    "drama": ["Drama"],
    "emotional": ["Drama"],
    "sad": ["Drama"],
    "crying": ["Drama"],
    "tearjerker": ["Drama"],
    "touching": ["Drama"],
    "moving": ["Drama"],
    # Romance
    "romance": ["Romance"],
    "romantic": ["Romance"],
    "love": ["Romance"],
    "relationship": ["Romance"],
    "couple": ["Romance"],
    "love story": ["Romance"],
    # Psychological
    "psychological": ["Psychological"],
    "mind games": ["Psychological"],
    "dark": ["Psychological", "Thriller"],
    "twisted": ["Psychological", "Thriller"],
    "complex": ["Psychological"],
    "deep": ["Psychological"],
    "mindfuck": ["Psychological"],
    "genius": ["Psychological"],
    "twists": ["Psychological", "Thriller", "Mystery"],
    "plot twist": ["Psychological", "Thriller", "Mystery"],
    # Thriller
    "thriller": ["Thriller"],
    "suspense": ["Thriller"],
    "tense": ["Thriller"],
    "mystery": ["Mystery"],
    "detective": ["Mystery", "Police"],
    "crime": ["Mystery", "Police"],
    "murder": ["Mystery", "Thriller"],
    "investigation": ["Mystery", "Police"],
    # Sci-Fi
    "sci-fi": ["Sci-Fi"],
    "scifi": ["Sci-Fi"],
    "science fiction": ["Sci-Fi"],
    "futuristic": ["Sci-Fi"],
    "technology": ["Sci-Fi"],
    "cyberpunk": ["Sci-Fi"],
    "space": ["Space", "Sci-Fi"],
    "alien": ["Space", "Sci-Fi"],
    "robot": ["Sci-Fi", "Mecha"],
    "robots": ["Sci-Fi", "Mecha"],
    "mecha": ["Mecha"],
    "giant robots": ["Mecha"],
    "mech": ["Mecha"],
    # Fantasy
    "fantasy": ["Fantasy"],
    "magic": ["Magic", "Fantasy"],
    "magical": ["Magic", "Fantasy"],
    "wizard": ["Magic", "Fantasy"],
    "powers": ["Super Power", "Fantasy"],
    "supernatural": ["Supernatural"],
    "demons": ["Demons", "Supernatural"],
    "vampire": ["Vampire", "Supernatural"],
    "isekai": ["Fantasy", "Adventure"],
    "another world": ["Fantasy"],
    # Shounen
    "shounen": ["Shounen"],
    "shonen": ["Shounen"],
    "power up": ["Shounen", "Super Power"],
    "super power": ["Super Power"],
    "superpower": ["Super Power"],
    "martial arts": ["Martial Arts"],
    # Shoujo
    "shoujo": ["Shoujo"],
    "shojo": ["Shoujo"],
    "female": ["Shoujo"],
    "girl": ["Shoujo"],
    # Slice of Life
    "slice of life": ["Slice of Life"],
    "everyday": ["Slice of Life"],
    "daily life": ["Slice of Life"],
    "relaxing": ["Slice of Life"],
    "calm": ["Slice of Life"],
    "chill": ["Slice of Life"],
    "school": ["School", "Slice of Life"],
    "high school": ["School"],
    "students": ["School"],
    "college": ["School"],
    # Horror
    "horror": ["Horror"],
    "scary": ["Horror"],
    "creepy": ["Horror"],
    "gore": ["Horror"],
    "disturbing": ["Horror", "Psychological"],
    # Sports
    "sports": ["Sports"],
    "sport": ["Sports"],
    "basketball": ["Sports"],
    "volleyball": ["Sports"],
    "soccer": ["Sports"],
    "football": ["Sports"],
    "baseball": ["Sports"],
    "swimming": ["Sports"],
    "boxing": ["Sports"],
    # Music
    "music": ["Music"],
    "band": ["Music"],
    "singing": ["Music"],
    # Historical
    "historical": ["Historical"],
    "history": ["Historical"],
    "samurai": ["Historical", "Action"],
    "ninja": ["Historical", "Action", "Shounen"],
    "war": ["Military", "Action"],
    "military": ["Military"],
    # Kids
    "kids": ["Kids"],
    "children": ["Kids"],
    "family": ["Kids"],
    # Ecchi
    "ecchi": ["Ecchi"],
    "harem": ["Harem"],
}

# Genre list from dataset (all valid genre labels)
VALID_GENRES = [
    "Action",
    "Adventure",
    "Comedy",
    "Drama",
    "Romance",
    "Fantasy",
    "Magic",
    "Supernatural",
    "Psychological",
    "Thriller",
    "Mystery",
    "Sci-Fi",
    "Space",
    "Mecha",
    "Slice of Life",
    "School",
    "Sports",
    "Shounen",
    "Shoujo",
    "Seinen",
    "Josei",
    "Horror",
    "Historical",
    "Military",
    "Music",
    "Super Power",
    "Martial Arts",
    "Demons",
    "Vampire",
    "Police",
    "Harem",
    "Ecchi",
    "Kids",
    "Parody",
    "Game",
    "Samurai",
    "Cars",
]
